---
title: 'EDS 230 Assignment 3: Informal Sensitivity Analysis'
author: "Erika Egg and Jared Petry"
date: "2023-05-02"
output:
  pdf_document: default
  html_document: default
---

**This is an informal sensitivity analysis for the two parameters in our profit model: selling_price and production_cost.**

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Load libraries
```{r}
library(here)
library(tidyverse)
library(purrr) 
library(ggplot2) 
library(ggpubr) 
```

## Source necessary functions
```{r}
# source necessary functions
source("calc_almond_yield_anomaly_for_profit_func.R")
source("calc_almond_profit.R")
```

### Run both models to make sure sourcing worked: 
```{r message=FALSE}
calc_almond_yield_anomaly_for_profit_func() 
calc_almond_profit()
```

## Sensitivity analysis with parameters: "selling_price" and "production_cost"
```{r}
# Create a sampling distribution for both parameters
# Assume a uniform distribution - we don't know anything about variation
nsamples = 300
deviation = 0.15


base_sellprice = 5000 # default in profit function
selling_price = runif(min = base_sellprice-deviation*base_sellprice,
                      max = base_sellprice+deviation*base_sellprice, 
                      n = nsamples) # get a sampling distribution length 300

base_prodcost = 4000 # default in profit function
production_cost = runif(min = base_prodcost-deviation*base_prodcost,
                        max = base_prodcost+deviation*base_prodcost, 
                        n = nsamples) # get a sampling distribution length 300


params = cbind.data.frame(selling_price, production_cost) # combine into one df

# Use pmap to acquire results: takes function name and then names of all 
# parameters that don't change
results = params %>% pmap(calc_almond_profit,
                          acres = 200,
                          expected_yield = 1)

# Check results
results[[1]]
length(results)

# Extract results from the list as above
mean_profit = map_df(results,`[`, c("mean")) 

# Add the parameter values for each run
mean_profit = cbind.data.frame(mean_profit, params)

# Plots for means - two versions of same thing
p1 = ggplot(mean_profit, aes(selling_price, mean, col = production_cost)) + 
  geom_point(cex = 2) +
  labs(title = "Mean Annual Profit vs. Almond Selling Price and Production Cost",
       y = "Mean Annual Profit ($)",
       x = "Almond Selling Price ($/ton)",
       col = "Almond Production Cost ($/ton)") +
  scale_y_continuous(labels = scales::comma)
p2 = ggplot(mean_profit, aes(production_cost, mean, col = selling_price)) + 
  geom_point(cex = 2) +
  labs(y = "Mean Annual Profit ($)",
       x = "Almond Production Cost ($/ton)",
       col = "Almond Selling Price ($/ton)") +
  scale_y_continuous(labels = scales::comma)

ggarrange(p1, p2, ncol = 1)

ggsave(here("almond_profit_scatterplot.png"))

# Extract annual information too and plot
annual_df = map_df(results,`[`, c("annual")) 
annual_profit = as.data.frame(annual_df$annual$year)
colnames(annual_profit)="year"
annual_profit$profit_w_anom = annual_df$annual$profit_w_anom

p3 = ggplot(annual_profit, aes(as.factor(year), profit_w_anom)) +
  geom_boxplot() +
  labs(title = "Almond Profit, 1989-2010",
       x = "Year",
       y = "Profit ($/ton)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_y_continuous(labels = scales::comma)

p3

ggsave(here("almond_profit_boxplot.png"))
```

